// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdxBJieJSlh05-rsGx7Vp7EDDC5AzOXw8',
    appId: '1:163893428970:web:745635cf95b2c47fbe0d93',
    messagingSenderId: '163893428970',
    projectId: 'cmsc23-exercise-8-816c2',
    authDomain: 'cmsc23-exercise-8-816c2.firebaseapp.com',
    storageBucket: 'cmsc23-exercise-8-816c2.firebasestorage.app',
    measurementId: 'G-XZE2ZW3C72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBjElLThtZz8GNir2DcTlAZZ0wKdcaWwk',
    appId: '1:163893428970:android:488954d704243157be0d93',
    messagingSenderId: '163893428970',
    projectId: 'cmsc23-exercise-8-816c2',
    storageBucket: 'cmsc23-exercise-8-816c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb5zLDp2q1fG0415BjTtKF9rXZvgU4Mt0',
    appId: '1:163893428970:ios:41cf9f03d3813fe0be0d93',
    messagingSenderId: '163893428970',
    projectId: 'cmsc23-exercise-8-816c2',
    storageBucket: 'cmsc23-exercise-8-816c2.firebasestorage.app',
    iosBundleId: 'com.example.exercise8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb5zLDp2q1fG0415BjTtKF9rXZvgU4Mt0',
    appId: '1:163893428970:ios:41cf9f03d3813fe0be0d93',
    messagingSenderId: '163893428970',
    projectId: 'cmsc23-exercise-8-816c2',
    storageBucket: 'cmsc23-exercise-8-816c2.firebasestorage.app',
    iosBundleId: 'com.example.exercise8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdxBJieJSlh05-rsGx7Vp7EDDC5AzOXw8',
    appId: '1:163893428970:web:33b4961cd9dfac10be0d93',
    messagingSenderId: '163893428970',
    projectId: 'cmsc23-exercise-8-816c2',
    authDomain: 'cmsc23-exercise-8-816c2.firebaseapp.com',
    storageBucket: 'cmsc23-exercise-8-816c2.firebasestorage.app',
    measurementId: 'G-0TGQ8NZBVC',
  );
}

// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

// // ...

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );